# Generated by Django 4.2 on 2023-04-05 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=20)),
                ('MAC', models.CharField(max_length=100)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
