# Generated by Django 4.2 on 2023-04-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0003_pressure_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressure',
            old_name='measure_time',
            new_name='registration_time',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='measure_time',
            new_name='registration_time',
        ),
    ]
