# Generated by Django 4.2 on 2023-04-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0004_rename_measure_time_pressure_registration_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='connected_at',
            new_name='connected_time',
        ),
        migrations.AlterField(
            model_name='device',
            name='IP',
            field=models.GenericIPAddressField(),
        ),
    ]
