# Generated by Django 4.2 on 2023-04-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0005_rename_connected_at_device_connected_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pressure',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
        migrations.AddField(
            model_name='device',
            name='MAC',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
